5 1 access
thinknetica-django-lab-02/lanaku16 pull request #43
Opened 2021-04-05 06:36 UTC by lanaku16

Closes #41

2021-04-05 19:16 UTC, morgangt requested changes

2021-04-05 19:16 UTC, morgangt commented on marketplace/main/templates/main/login.html
> +</html>
зачем здесь этот шаблон?

2021-04-05 19:16 UTC, morgangt commented on marketplace/main/views.py
> +from main.models import *
импорт со звездочкой - антипатерн

2021-04-05 19:16 UTC, morgangt commented on marketplace/main/views.py
> +                up.user = u
однобуквенные переменные это плохо, предлагаю data_user или data_user_form

2021-04-06 13:31 UTC, lanaku16 commented on marketplace/main/templates/main/login.html
> +</html>
> зачем здесь этот шаблон?

он используется для авторизации пользователя(в следующем задании был доделан)

2021-04-06 21:31 UTC, morgangt approved these changes

2021-04-07 06:03 UTC, merged